# Generated by Django 5.2.14 on 2026-05-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='secondary_role',
            field=models.CharField(blank=True, choices=[('it_admin', 'IT Administrator'), ('employee', 'Employee'), ('hr', 'Human Resource'), ('approver', 'Approver')], max_length=20, null=True),
        ),
    ]
