# Generated by Django 5.2.14 on 2026-06-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_secondary_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
    ]
