# Generated by Django 5.2.14 on 2026-06-05 06:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0002_leaveapplication_chosen_approver'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='chosen_supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_leaves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='supervisor_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='chosen_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Supervisor Review'), ('supervisor_approved', 'Approved by Supervisor'), ('supervisor_declined', 'Declined by Supervisor'), ('forwarded_to_hr', 'Forwarded to HR'), ('forwarded_to_approver', 'Forwarded to Approver'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=30),
        ),
    ]
