# Generated by Django 5.2.14 on 2026-07-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0004_alter_leavetype_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField(unique=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='is_special_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='special_request_reason',
            field=models.TextField(blank=True),
        ),
    ]
